### ISSUE TITLE
Google Firestore Cloud Functions

### ISSUE THREAD

**Issue by jrock2468** [sawyerh/highlights#2]
Any thoughts on adding your node cloud functions that are fired when records are added to Firestore to this project?

**Comment by sawyerh** [comment]
Thanks for the request. I'd like to at some point, but don't currently have the free time to make this happen.

**Comment by sawyerh** [comment]
@jrock2468 Hello 3 years later, hope you're well. I just added the Firebase functions for this project to the repo: https://github.com/sawyerh/highlights/tree/main/firebase
