### ISSUE TITLE
Have you ever played around with tapping into whispersync to automate that email push

### ISSUE THREAD

**Issue by vongohren** [sawyerh/highlights#73]
I have always wanted to make the sync of notes automatic. So I could once write a hashtag in my notes that would remind me the day after or something. 

But as I understand your system, you still have to send an email to a function that is parsing the HTML file right?

**Comment by sawyerh** [comment]
> you still have to send an email to a function that is parsing the HTML file right?

@vongohren Yes, this is currently an email-initiated workflow at the moment. Can you say more about the Whispersync idea? I'm not very familiar with it.

**Comment by vongohren** [comment]
@sawyerh so I understand that there is an automated syncronization happning in the Amazon world. As my kindle can take notes, and then suddenly my phone can have them available on its phone. So something has to happen there, and I believe its the thing called whispersync.

Let me make an assumption and a user journey I want to work with.

I assume you send the email that adds the notes as html from your phone, as that is the only way possible today? Or maybe you have a newer kindle that can do this?

I would like to achive a way for my kindle, when connected to internet, can send notes automatically, and a server listenes and parses the highlightes and notes, to be able to maybe react to them if I write something special in the notes. As I often catch myself thinking about something while reading that I should pursue the day after or something.
Since I cannot send notes from my kindle, only my phone, I have some delay in the process, and often the phone is not with me while reading.

Did any of this make any sense :D ?

**Comment by sawyerh** [comment]
@vongohren Makes sense, I'd love something more automated too 😄 From my understanding though, the syncing behavior isn't made available outside of Amazon's walled garden, unfortunately.

As for the Whispersync feature, sounds like that's what Amazon calls the ability to go between reading and listening to a book: https://www.audible.com/ep/wfs

**Comment by sawyerh** [comment]
If you figure it out, I'd be interested in hearing what you learn 🙂
